<?php
$tabla_efectividad = [
    'Normal' => [
        'Roca' => 0.5,
        'Fantasma' => 0,
        'Acero' => 0.5,
    ],
    'Fuego' => [
        'Fuego' => 0.5,
        'Agua' => 0.5,
        'Planta' => 2,
        'Hielo' => 2,
        'Roca' => 0.5,
        'Dragón' => 0.5,
        'Acero' => 2,
    ],
    'Agua' => [
        'Planta' => 0.5,
        'Agua' => 0.5,
        'Eléctrico' => 0.5,
        'Tierra' => 2,
        'Roca' => 2,
        'Dragón' => 0.5,
    ],
    'Planta' => [
        'Fuego' => 0.5,
        'Agua' => 2,
        'Eléctrico' => 1,
        'Hielo' => 1,
        'Veneno' => 0.5,
        'Volador' => 0.5,
        'Bicho' => 0.5,
        'Roca' => 2,
        'Dragón' => 0.5,
        'Acero' => 0.5,
    ],
    'Eléctrico' => [
        'Eléctrico' => 0.5,
        'Tierra' => 0,
        'Volador' => 2,
        'Agua' => 2,
    ],
    'Hielo' => [
        'Fuego' => 0.5,
        'Planta' => 2,
        'Lucha' => 0.5,
        'Tierra' => 2,
        'Volador' => 2,
        'Dragón' => 2,
        'Acero' => 0.5,
    ],
    'Lucha' => [
        'Volador' => 0.5,
        'Psíquico' => 0.5,
        'Bicho' => 0.5,
        'Roca' => 2,
        'Fantasma' => 0,
        'Siniestro' => 2,
        'Acero' => 2,
        'Hada' => 0.5,
    ],
    'Veneno' => [
        'Planta' => 2,
        'Tierra' => 0.5,
        'Bicho' => 0.5,
        'Roca' => 0.5,
        'Fantasma' => 0.5,
        'Acero' => 0,
        'Hada' => 2,
    ],
    'Tierra' => [
        'Eléctrico' => 2,
        'Volador' => 0,
        'Agua' => 1,
        'Planta' => 0.5,
        'Roca' => 2,
    ],
    'Volador' => [
        'Eléctrico' => 0.5,
        'Lucha' => 2,
        'Bicho' => 2,
        'Roca' => 0.5,
    ],
    'Psíquico' => [
        'Lucha' => 2,
        'Veneno' => 2,
        'Siniestro' => 0,
    ],
    'Bicho' => [
        'Fuego' => 0.5,
        'Lucha' => 0.5,
        'Psíquico' => 2,
        'Siniestro' => 2,
        'Roca' => 1,
        'Acero' => 0.5,
        'Hada' => 0.5,
    ],
    'Roca' => [
        'Lucha' => 0.5,
        'Bicho' => 2,
        'Fuego' => 2,
        'Hielo' => 2,
        'Volador' => 2,
    ],
    'Fantasma' => [
        'Normal' => 0,
        'Lucha' => 0.5,
        'Fantasma' => 2,
        'Siniestro' => 0.5,
    ],
    'Dragón' => [
        'Dragón' => 2,
        'Hada' => 0,
    ],
    'Siniestro' => [
        'Lucha' => 0.5,
        'Psíquico' => 2,
        'Fantasma' => 2,
        'Hada' => 0.5,
    ],
    'Acero' => [
        'Fuego' => 0.5,
        'Agua' => 0.5,
        'Planta' => 1,
        'Lucha' => 1,
        'Roca' => 2,
        'Hada' => 2,
    ],
    'Hada' => [
        'Lucha' => 1,
        'Dragón' => 2,
        'Siniestro' => 1,
        'Acero' => 0.5,
    ],
];
